# https://taskfile.dev

version: '3'

tasks:
  migrate_up:
    cmds:
      - migrate -database postgres://user_admin:19851982@localhost:5444/auctiondb?sslmode=disable -source file://auction_service_api/db/migrations up

    silent: true
  migrate_down:
    cmds:
      - migrate -database postgres://user_admin:19851982@localhost:5444/auctiondb?sslmode=disable -source file://auction_service_api/db/migrations down
    silent: true
